### Esta es la API de "Open Public APIs". Con este se toda la lista de jsons.
GET http://fakestoreapi.com/products

### Get obtener de mi servidor backend toda la lista de productos.
GET http://localhost:3000/products/17

### Path para actualizar una propiedad de un producto
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
    "price": 73.54
}

### Patch para reemplazar un producto por completo
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
    "id": 90,
    "title": "El hombre araña",
    "price": 2000,
    "description": "It's a movie",
    "category": "drama",
    "imagen": "fjalksjdlfkjaslkdjflkasj",
    "rating": {
        "rate": 6.2,
        "count": 100
    }

}

### Post para crear un nuevo producto
POST http://localhost:3000/products/
Content-Type: application/json

{
    "id": 989,
    "title": "Pacific RIM",
    "price": 9000,
    "description": "It's the best movie ever watched",
    "category": "action",
    "imagen": "lkjiwoas{asñlmas}",
    "rating": {
        "rate": 9.8,
        "count": 900
    }

}

### Delete para eliminar un producto
DELETE http://localhost:3000/products/9

### GET para obtener todos los productos filtrados por parametros
GET http://localhost:3000/products?title=Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops

### Otro diferente
GET http://localhost:3000/products?rating={"rate":3.9,"count":120}